export const CREATE_COURSE = 'CREATE_COURSE';
export const EDIT_COURSE = 'EDIT_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHOR_SUCCESS = 'LOAD_AUTHOR_SUCCESS';

export const INCREMENT_COUNT = 'INCREMENT_COUNT';