export const CREATE_COURSE = 'CREATE_COURSE';
export const EDIT_COURSE = 'EDIT_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';

export const INCREMENT_COUNT = 'INCREMENT_COUNT';